#!/bin/bash

set -xe

pwd
env

cf api $PWS_API --skip-ssl-validation

cf login -u $PWS_USER -p $PWS_PWD -o "$PWS_ORG" -s "$PWS_SPACE"

cf apps

set +e

main_blue_app_exist=$(cf apps | grep "$PWS_APP_SUFFIX" | grep "$PWS_APP_HOSTNAME" | grep "BLUE" | grep -v "\-staging" | wc -l)
if [ $main_blue_app_exist -gt 0 ]
then
  echo "BLUE" > ./current-app-info/current-app.txt
  echo "GREEN-staging" > ./current-app-info/next-app.txt
else
  echo "GREEN" > ./current-app-info/current-app.txt
  echo "BLUE-staging" > ./current-app-info/next-app.txt
fi

main_app_exist=$(cf apps | grep "$PWS_APP_SUFFIX" | grep "$PWS_APP_HOSTNAME" | grep -v "\-staging" | wc -l)
main_instance_count=1
if [ $main_app_exist -gt 0 ]
then
 main_instance_count=$(cf apps | grep "$PWS_APP_SUFFIX" | grep "$PWS_APP_HOSTNAME" | grep -v "\-staging" | awk -F"/" '{print $2} ' |awk '{print $1}') 
fi
echo $main_instance_count > ./current-app-info/next-app-instance-count.txt


set -xe
echo "Current main app routes to app instance $(cat ./current-app-info/current-app.txt)"
echo "New version of app to be deployed to instance $(cat ./current-app-info/next-app.txt) "
echo "New version of app to be deployed to instance-count $(cat ./current-app-info/next-app-instance-count.txt)"

