#!/bin/bash

set -xe

sed "s/APPNAME/canary-staging-$PWS_APP_SUFFIX/" ./build-out-repo/manifests/manifest.yml > ./output/manifest.yml

cat ./output/manifest.yml

mv ./build-out-repo/output/* ./output

