#!/bin/bash

set -xe

cat ./current-app-info/current-app.txt

sed "s/APPNAME/$PWS_APP_SUFFIX-$(cat ./current-app-info/next-app.txt)/" ./build-out-repo/manifests/manifest.yml > ./output/manifest.yml

cat ./output/manifest.yml


mv ./build-out-repo/output/* ./output

