---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.3-jdk-8

inputs:
- name: demo-repo

outputs:
- name: out-repo

run:
  path: /bin/bash
  args: 
    - demo-repo/ci/tasks/cachetest-task1

caches:
  - path: .gradle/
  - path: .m2/
 
