groups:
- name: main
  jobs:
  - build
  - deploy-new-app
  - blue-green-update
  - unmap-old-app

resources:

- name: source-repo
  type: git
  source:
    branch: master
#    uri: git@github.com:myminseok/articulate.git
    uri: {{git-source-repo-uri}}
    private_key: {{github-private-key}}
  check_every: 10s # for demo

- name: build-out-repo
  type: git
  source:
    branch: master
    uri: git@github.com:myminseok/articulate-ci-demo.git
    private_key: {{github-private-key}}
    disable_ci_skip: true
  check_every: 10s # for demo

- name: PCF
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

- name: CVE-check
  type: docker-image
  source:
    repository: java

jobs:
- name: build
  serial: true
  public: true
  plan:
  - get: source-repo
    trigger: true
  - get: build-out-repo
    trigger: false
  - get: CVE-check
  - task: build-test
    file: build-out-repo/ci/tasks/build-test.yml
    params:
      BUILD_JAR_NAME: demo.jar
  - put: build-out-repo
    params:
      repository: out-repo
      rebase: true
      #force: true
- name: deploy-new-app
  serial: true
  public: true
  plan:
  - get: build-out-repo
    trigger: true  
    passed:
      - build
  - task: get-current-app-color
    file: build-out-repo/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_HOSTNAME: {{pws-app-hostname}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
      
  - task: prepare-app-manifest
    file: build-out-repo/ci/tasks/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_HOSTNAME: {{pws-app-hostname}}
  - put: PCF
    params:
      manifest: output/manifest.yml
      path: output/demo.jar

- name: blue-green-update
  serial: true
  public: true
  plan:
  - get: build-out-repo
    trigger: true
    passed:
      - deploy-new-app
  - task: get-current-app-color
    file: build-out-repo/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_HOSTNAME: {{pws-app-hostname}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: switch-app-routes
    file: build-out-repo/ci/tasks/update-routes.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_DOMAIN: {{pws-app-domain}}
      PWS_APP_HOSTNAME: {{pws-app-hostname}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}


- name: unmap-old-app
  serial: true
  public: true
  plan:
  - get: build-out-repo
    trigger: true
    passed:
      - blue-green-update
  - task: get-current-app-color
    file: build-out-repo/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_HOSTNAME: {{pws-app-hostname}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: unmap-routes
    file: build-out-repo/ci/tasks/unmap-routes.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_DOMAIN: {{pws-app-domain}}
      PWS_APP_HOSTNAME: {{pws-app-hostname}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
